# Generated by Django 4.0.6 on 2022-07-06 18:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('eng_name', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='English Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='Slug')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('radius', models.IntegerField(blank=True, null=True, verbose_name='Radius')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('region_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region Name')),
                ('city_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='City Name')),
                ('extras', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'IPAddresses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('extras', models.JSONField(null=True, verbose_name='Extras')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326, verbose_name='Location')),
                ('data_source', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Data Source')),
                ('language', models.CharField(default='hi', max_length=5, verbose_name='Language')),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Place Id')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='Address line 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='Address line 2')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326)),
                ('location_type', models.CharField(blank=True, choices=[('District', 'District'), ('Block', 'Block'), ('State', 'State'), ('Village', 'Village')], max_length=100, null=True, verbose_name='Location Type')),
                ('location_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Location_Id')),
                ('extras', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extras')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='base.country')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ('country', 'address_1'),
            },
        ),
    ]
