# Generated by Django 4.0.6 on 2022-07-10 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='variable name')),
                ('display_name', models.CharField(max_length=256, verbose_name='variable display name')),
                ('description', models.CharField(max_length=1024, verbose_name='variable description')),
                ('value', models.CharField(max_length=256, verbose_name='variable value')),
                ('detailed_value', models.TextField(blank=True, null=True, verbose_name='Detailed Value')),
            ],
            options={
                'verbose_name': 'App Variable',
                'verbose_name_plural': 'App Variables',
                'ordering': ('name',),
            },
        ),
    ]
