# Generated by Django 4.0.6 on 2022-07-09 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobtype_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExtraField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=50, verbose_name='Heading')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_extra', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
