# Generated by Django 4.0.6 on 2022-07-09 14:24

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_is_remote_jobapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('new_applicant', 'New Application'), ('selected', 'Selected'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('in_process', 'In Process')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='identifier',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('part_time', 'Part Time')], max_length=50, verbose_name='Identifier'),
        ),
    ]
