# Generated by Django 4.0.6 on 2022-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jobtype_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='display_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('reserved', 'Reserved'), ('in_process', 'In Process'), ('new_applicant', 'New Application')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
    ]
