# Generated by Django 4.0.6 on 2022-07-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobapplication_resume_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('new_applicant', 'New Application'), ('selected', 'Selected'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('in_process', 'In Process')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
    ]
