# Generated by Django 4.0.6 on 2022-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobapplication_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('rejected', 'Rejected'), ('new_applicant', 'New Application'), ('selected', 'Selected'), ('in_process', 'In Process')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
    ]
