TQN_BUY_SELL = 'BUY_SELL'
TQN_FARMING_EQUIPMENT = 'FARMING_EQUIPMENT'
TQN_SEED = 'SEED'
TQN_AGROCHEMICAL = 'AGROCHEMICAL'
TQN_ANIMAL_FEED = 'ANIMAL_FEED'
TQN_TRACTOR = 'TRACTOR'
TQN_PASHUPAALAN = 'PASHUPAALAN'
TQN_MANDIBHAAV = 'MANDIBHAAV'
TQN_DISCUSSION = 'DISCUSSION'
TQN_FASAL_PROTECTION = 'FASAL_PROTECTION'
TQN_WEED_MANAGEMENT = 'WEED_MANAGEMENT'
TQN_FERTILIZER = 'FERTILIZER'
TQN_DISEASE = 'DISEASE'
TQN_CROP_DISEASE = 'CROP_DISEASE'
TQN_ANIMAL_DISEASE = 'ANIMAL_DISEASE'
TQN_ANIMAL_PROTECTION = 'ANIMAL_PROTECTION'
TQN_PURCHASING = 'PURCHASING'
TQN_SELLING = 'SELLING'
TQN_KRISHI_QUIZ = "QUIZ"

LOCATION_TYPE_CHOICES_DISTRICT = 'District'
LOCATION_TYPE_CHOICES_BLOCK = 'Block'
LOCATION_TYPE_CHOICES_STATE = 'State'
LOCATION_TYPE_CHOICES_VILLAGE = 'Village'
LOCATION_TYPE_CHOICES = [
    (LOCATION_TYPE_CHOICES_DISTRICT, 'District'),
    (LOCATION_TYPE_CHOICES_BLOCK, 'Block'),
    (LOCATION_TYPE_CHOICES_STATE, 'State'),
    (LOCATION_TYPE_CHOICES_VILLAGE, 'Village')
]
COMMENT_AUTHOR_TYPE_USER = 'user'
COMMENT_AUTHOR_TYPE_BUSINESS = 'business'

COMMENT_AUTHOR_TYPE_CHOICES = (
    (COMMENT_AUTHOR_TYPE_USER, 'User Comment'),
    (COMMENT_AUTHOR_TYPE_BUSINESS, 'Business Comment')
)


class LocationType:
    Village = 'Village'
    District = 'District'
    Block = 'Block'
    State = 'State'
    AllIndia = 'AllIndia'


class CommentType:
    COMMENT = 'comment'
    NESTED_COMMENT = 'nested_comment'


class VideoSizeFormat:
    V360p = '360p'
    V540p = '540p'
    V720p = '720p'
    UseSrc = 'UseSrc'
