# Generated by Django 4.0.6 on 2022-07-09 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('jobs', '0007_alter_jobtype_identifier_jobextrafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_application', to='base.address'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_message',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Applicant Message'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_process', 'In Process'), ('selected', 'Selected'), ('new_applicant', 'New Application'), ('reserved', 'Reserved')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_staff_note',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Latest Note By Staff'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Include the country code.', max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='identifier',
            field=models.CharField(choices=[('part_time', 'Part Time'), ('internship', 'Internship'), ('full_time', 'Full Time')], max_length=50, verbose_name='Identifier'),
        ),
    ]
