# Generated by Django 4.0.6 on 2022-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobapplication_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('selected', 'Selected'), ('new_applicant', 'New Application'), ('in_process', 'In Process'), ('rejected', 'Rejected')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='display_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
