# Generated by Django 4.0.6 on 2022-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_display_name_alter_job_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_cloudinary_url',
            field=models.URLField(blank=True, null=True, verbose_name='Resume URL'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('reserved', 'Reserved'), ('new_applicant', 'New Application'), ('in_process', 'In Process'), ('selected', 'Selected')], db_index=True, default='new_applicant', max_length=50, verbose_name='Application Status'),
        ),
    ]
