# Generated by Django 4.0.6 on 2022-07-06 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Department Name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Text')),
                ('identifier', models.CharField(choices=[('creator_warehouse', 'Creator Warehouse'), ('ltt_store', 'LTT Store'), ('floatplane_media', 'Floatplane Media'), ('linus_media_group', 'Linus Media Group')], max_length=100, verbose_name='Identifier')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('is_shown', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
